#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-sphinxcontrib_websupport
Version  : 1.2.6
Release  : 68
URL      : https://files.pythonhosted.org/packages/8a/a8/5b8b11590c880b4511c93523214d6455ff7d108fd0a20e5b39064ce3c92e/sphinxcontrib_websupport-1.2.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/8a/a8/5b8b11590c880b4511c93523214d6455ff7d108fd0a20e5b39064ce3c92e/sphinxcontrib_websupport-1.2.6.tar.gz
Summary  : sphinxcontrib-websupport provides a Python API to easily integrate Sphinx documentation into your Web application
Group    : Development/Tools
License  : BSD-2-Clause
Requires: pypi-sphinxcontrib_websupport-license = %{version}-%{release}
Requires: pypi-sphinxcontrib_websupport-python = %{version}-%{release}
Requires: pypi-sphinxcontrib_websupport-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(flit_core)
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
===================================
===================================
This is the Sphinx documentation generator, see http://www.sphinx-doc.org/.

%package license
Summary: license components for the pypi-sphinxcontrib_websupport package.
Group: Default

%description license
license components for the pypi-sphinxcontrib_websupport package.


%package python
Summary: python components for the pypi-sphinxcontrib_websupport package.
Group: Default
Requires: pypi-sphinxcontrib_websupport-python3 = %{version}-%{release}

%description python
python components for the pypi-sphinxcontrib_websupport package.


%package python3
Summary: python3 components for the pypi-sphinxcontrib_websupport package.
Group: Default
Requires: python3-core
Provides: pypi(sphinxcontrib_websupport)
Requires: pypi(jinja2)
Requires: pypi(sphinx)
Requires: pypi(sphinxcontrib_serializinghtml)

%description python3
python3 components for the pypi-sphinxcontrib_websupport package.


%prep
%setup -q -n sphinxcontrib_websupport-1.2.6
cd %{_builddir}/sphinxcontrib_websupport-1.2.6
pushd ..
cp -a sphinxcontrib_websupport-1.2.6 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1695224709
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-sphinxcontrib_websupport
cp %{_builddir}/sphinxcontrib_websupport-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sphinxcontrib_websupport/e5d1b0fd46b681f4be3ce69e064b9427372ea1f2 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-sphinxcontrib_websupport/e5d1b0fd46b681f4be3ce69e064b9427372ea1f2

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
