#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x102C2C17498D6B9E (i.tkomiya@gmail.com)
#
Name     : sphinxcontrib-websupport
Version  : 1.2.1
Release  : 36
URL      : https://files.pythonhosted.org/packages/60/65/78e1514be951a3584df2e27b1b86e22609dd73312461e1af2afb9a53152c/sphinxcontrib-websupport-1.2.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/60/65/78e1514be951a3584df2e27b1b86e22609dd73312461e1af2afb9a53152c/sphinxcontrib-websupport-1.2.1.tar.gz
Source1  : https://files.pythonhosted.org/packages/60/65/78e1514be951a3584df2e27b1b86e22609dd73312461e1af2afb9a53152c/sphinxcontrib-websupport-1.2.1.tar.gz.asc
Summary  : Sphinx API for Web Apps
Group    : Development/Tools
License  : BSD-2-Clause
Requires: sphinxcontrib-websupport-license = %{version}-%{release}
Requires: sphinxcontrib-websupport-python = %{version}-%{release}
Requires: sphinxcontrib-websupport-python3 = %{version}-%{release}
Requires: flake8
BuildRequires : buildreq-distutils3
BuildRequires : flake8
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
===================================
===================================
This is the Sphinx documentation generator, see http://www.sphinx-doc.org/.

%package license
Summary: license components for the sphinxcontrib-websupport package.
Group: Default

%description license
license components for the sphinxcontrib-websupport package.


%package python
Summary: python components for the sphinxcontrib-websupport package.
Group: Default
Requires: sphinxcontrib-websupport-python3 = %{version}-%{release}

%description python
python components for the sphinxcontrib-websupport package.


%package python3
Summary: python3 components for the sphinxcontrib-websupport package.
Group: Default
Requires: python3-core
Provides: pypi(sphinxcontrib_websupport)

%description python3
python3 components for the sphinxcontrib-websupport package.


%prep
%setup -q -n sphinxcontrib-websupport-1.2.1
cd %{_builddir}/sphinxcontrib-websupport-1.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1584895088
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sphinxcontrib-websupport
cp %{_builddir}/sphinxcontrib-websupport-1.2.1/LICENSE %{buildroot}/usr/share/package-licenses/sphinxcontrib-websupport/e5d1b0fd46b681f4be3ce69e064b9427372ea1f2
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sphinxcontrib-websupport/e5d1b0fd46b681f4be3ce69e064b9427372ea1f2

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
